version: '3'
# https://www.home-assistant.io/installation/linux#docker-compose
services:
  homeassistant:
    container_name: homeassistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    #network_mode: host
    ports:
      - "8123:8123"
