
---
esphome:
  name: ${deviceid}
  platform: ESP8266
  board: nodemcuv2
  arduino_version: platformio/espressif8266@2.6.2
  platformio_options: {}
  esp8266_restore_from_flash: false
  board_flash_mode: dout
  includes: []
  libraries: []
  name_add_mac_suffix: false

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      priority: 8
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password2
      priority: 7
    - ssid: !secret wifi_ssid3
      password: !secret wifi_password3
      priority: 6
    - ssid: !secret wifi_ssid4
      password: !secret wifi_password4
      priority: 5
  enable_mdns: true
  domain: .local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Hotspot"
    password: !secret wifi_password_fallback

captive_portal: {}

# Enable logging
logger:
  level: DEBUG
  baud_rate: 115200
  id: logger_uart

# Enable Home Assistant API
api:
  password: !secret api_password
  port: 6053
  reboot_timeout: 15min

ota:
  password: !secret ota_password
  safe_mode: true
  port: 8266
  reboot_timeout: 5min
  num_attempts: 10

# time:
#  - platform: sntp
#      id: sntp_time
#      servers: de.pool.ntp.org
#  - timezone: Europe/Berlin

# home assistant time source
time:
  - platform: homeassistant
    id: homeassistant_time

i2c:
  sda: GPIO4 # GPIO4=D2
  scl: GPIO5 # GPIO5=D1
  scan: true
  id: bus_a

sensor:
  - platform: bme280
    i2c_id: bus_a
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: ${measureinterval}


