---
# to change a value on command line compile with substitution option -s 
# esphome -s devicenumber 03 environment-bme280-us-00.yaml
substitutions:
  deviceboard: nodemcuv2
  devicenumber: "00"
  deviceid: "environment-${deviceboard}-${devicenumber}"
  devicename: "Environment ${deviceboard} ${devicenumber}"
  measureinterval_bme: 60s
  measureinterval_us: 60s

<<: !include baseconfig-esp8266.yaml
#<<: !include sensor-bme280.yaml
<<: !include sensor-ultrasonic.yaml

