
---

i2c:
  sda: GPIO4 # GPIO4=D2
  scl: GPIO5 # GPIO5=D1
  scan: true
  id: bus_a

sensor:
  - platform: bme280
    i2c_id: bus_a
    temperature:
      name: "BME280 Temperature"
      oversampling: 16x
    pressure:
      name: "BME280 Pressure"
    humidity:
      name: "BME280 Humidity"
    address: 0x76
    update_interval: ${measureinterval_bme}


