---

switch:
  - platform: gpio
    id: relay
    name: "${devicename} Relay"
    pin: GPIO12
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - output.turn_on: s20_green_led
    on_turn_off:
      then:
        - output.turn_off: s20_green_led

#see binary_sensor
#status_led:
#  id: led_status
#  pin:
#    number: 12
#    inverted: true

light:
  - platform: monochromatic
    name: "${devicename} Green LED"
    output: s20_green_led

output:
  - platform: esp8266_pwm
    id: s20_green_led
    pin: GPIO13
    inverted: true

binary_sensor:
  - platform: gpio
    id: button_s1
    name: "${devicename} Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
#      mode:
#        input: true
#        pullup: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay
    internal: true
  - platform: status
    name: "${devicename} Status"
 # - platform: gpio
 #   pin: GPIO2
 #   name: "${devicename} Sensor"

