---
esphome:
  name: ${deviceid}
  platform: ESP8266
  board: esp01_1m
  arduino_version: platformio/espressif8266@2.6.2
  platformio_options: {}
  esp8266_restore_from_flash: false
  board_flash_mode: dout
  includes: []
  libraries: []
  name_add_mac_suffix: false

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
      priority: 8
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password2
      priority: 7
    - ssid: !secret wifi_ssid3
      password: !secret wifi_password3
      priority: 6
    - ssid: !secret wifi_ssid4
      password: !secret wifi_password4
      priority: 5
  enable_mdns: true
  domain: .local

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Fallback Hotspot"
    password: !secret wifi_password_fallback

captive_portal: {}

# Enable logging
logger:
  level: DEBUG
  baud_rate: 115200
  id: logger_uart

# Enable Home Assistant API
api:
  password: !secret api_password
  port: 6053
  reboot_timeout: 15min

ota:
  password: !secret ota_password
  safe_mode: true
  port: 8266
  reboot_timeout: 5min
  num_attempts: 10

# time:
#  - platform: sntp
#      id: sntp_time
#      servers: de.pool.ntp.org
#  - timezone: Europe/Berlin

# home assistant time source
time:
  - platform: homeassistant
    id: homeassistant_time

switch:
  - platform: gpio
    id: relay
    name: "${devicename} Relay"
    pin: GPIO12
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      then:
        - output.turn_on: s20_green_led
    on_turn_off:
      then:
        - output.turn_off: s20_green_led

#see binary_sensor
#status_led:
#  id: led_status
#  pin:
#    number: 12
#    inverted: true

light:
  - platform: monochromatic
    name: "${devicename} Green LED"
    output: s20_green_led

output:
  - platform: esp8266_pwm
    id: s20_green_led
    pin: GPIO13
    inverted: true

binary_sensor:
  - platform: gpio
    id: button_s1
    name: "${devicename} Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
#      mode:
#        input: true
#        pullup: true
      inverted: true
    on_press:
      then:
        - switch.toggle: relay
    internal: true
  - platform: status
    name: "${devicename} Status"
 # - platform: gpio
 #   pin: GPIO2
 #   name: "${devicename} Sensor"

